apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev-project-01
  namespace: argocd
spec:
  description: Dev Project 01
  sourceRepos:
  - '*'

  destinations:
  - namespace: '*'
    server: '*'

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: guestbook
  namespace: argocd
spec: 
  destination: 
    namespace: ns-01
    server: "https://kubernetes.default.svc"
  project: dev-project-01
  source: 
    path: guestbook
    repoURL: "https://github.com/ahmedaelhaj/argocd.git"
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true